### ISSUE TITLE
comparison to other solutions

### ISSUE THREAD

**Issue by matkoniecz** [decoderman/AB-Solution#3]
an you consider adding to readme comparison to other (more popular) solutions, for example https://github.com/StevenBlack/hosts including explanation why this solution is for some purposes better?

**Comment by decoderman** [comment]
No need for a comparison. AB-Solution is unique in the sense that it is an automated install- and management shell script for ad blocking and Dnsmasq logging on wireless, consumer grade Asus routers running on Asuswrt-Merlin firmware.
I am not aware of another script that does that on Asus routers in the way AB-Solution does.
Ad-blocking is done with an amalgamated hosts file, just as the one you linked to. 
What differs is that ad-blocking is done on the router level. Therefore eliminating the need to install ad-blocker solutions on the devices used within that LAN.
