### ISSUE TITLE
Use a variable instead of "0.0.0.0"

### ISSUE THREAD

**Issue by shounak-de** [decoderman/AB-Solution#5]
Hi, maybe I have missed something in the setup, but if I use the ab-solution script as is, I cannot get pixelserv-tls to serve the ad requests. I had to replace all 0.0.0.0 in your script with a ${bogus_ip} that I initialized it to $(nvram get lan_ipaddr) in the beginning.

I have a Merlin'd AC-66R with pixelsev-tls running on ports 80 and 443

Thanks for the script, btw. Its really easy to use :+1:

**Comment by decoderman** [comment]
You missed nothing during the setup. This version is not built for use with pixelserve.
But you did the right thing.
I currently have a beta script out (1.08-beta2) that works with pixelserve, although it is not stable and has some bugs.
At the moment I am working on AB-Solution 1.08-rc1. It will be a tremendous step up from 1.07. As with Ad-Blocking, pixelserv-tls can be switched on or off on the fly.

**Comment by shounak-de** [comment]
Got this error:

``
 AB-Solution 2.0                by thelonelycoder
--------------------------------------------------
 RT-AC66U (mips) fw-380.59 @ 192.168.1.1
--------------------------------------------------
 191404  blocked hosts  0  hosts blocked
 on Sep 06 12:40  next update: Tuesday @ 02:00
--------------------------------------------------

 [i]  install AB-Solution
 [cu] check for update

 [a]  toggle ad-blocking     [on]
 [l]  toggle logging         [on]
 [ws] toggle weekly stats    [off]

 [sl] toggle symlink         [on]
 [sh] toggle shell history   [off]
 [cb] use custom block IP    [off]

 [h]  change hosts file type [shooter40sw]
 [u]  update hosts file now
 [p]  process white- and blacklist

 [f]  follow the logfile
 [ls] current log stats

 [e]  exit AB-Solution              [sm] sub menu
__________________________________________________

 What do you want to do?   cb
__________________________________________________


 Custom block IP info:
 This sets a custom IP Address for blocked domains
 used with pixelserv-tls and others.
 IPv4 and IPv6 (if enabled) can be set.

 Update hosts [u], the hosts file 'hosts-adblock'
 and the blacklist.txt will reflect the IP change.
 -------------------------------------------------

 Custom IP is inactive at the moment.

 Would you like to enable it? [1=Yes 2=Exit] 1
 -------------------------------------------------

 Your custom IPv4 address is: none

 1=Set or change
 2=Keep or no change

 Select what to do: [1=Set 2=Keep] 1
 Enter custom IPv4 Address: 192.168.1.1

 192.168.1.1 is a valid IP address.

 Custom IPv4 set to 192.168.1.1
 converting hosts-adblock and blacklist.txt
 Custom IP activated.
 Restarting dnsmasq

Done.

 Refreshing Menu...

[: sh: unknown operand
sh: can't open '/tmp/mnt/NAS/ab-solution'
admin@RT-AC66R-D700:/tmp/home/root#
``

**Comment by shounak-de** [comment]
```
admin@RT-AC66R-D700:/tmp/home/root# ll /mnt/NAS/a*
-rw-rw-rw-    1 admin    root         70373 Sep  6 12:40 /mnt/NAS/ab-solution.sh

/mnt/NAS/adblocking:
drwxr-xr-x    2 admin    root          4096 Sep  6 12:30 stats/
drwxr-xr-x    2 admin    root          4096 Sep  6 12:30 scripts/
-rw-r--r--    1 admin    root           325 Sep  6 12:31 whitelist.txt
drwxr-xr-x    2 admin    root          4096 Sep  6 12:38 backup/
drwxr-xr-x    2 admin    root          4096 Sep  6 12:40 .config/
drwxr-xr-x    2 admin    root          4096 Sep  6 12:40 logs/
drwxrwxrwx   16 admin    root          4096 Sep  6 12:40 ../
-rw-r--r--    1 admin    root       6730043 Sep  6 12:52 hosts-adblock
-rw-r--r--    1 admin    root           284 Sep  6 12:52 blacklist.txt
drwxr-xr-x    7 admin    root          4096 Sep  6 12:52 ./
```

**Comment by shounak-de** [comment]
```
admin@RT-AC66R-D700:/tmp/home/root# cat /mnt/NAS/adblocking/.config/ab-solution.cfg
# DO NOT EDIT THIS FILE! DANGER ZONE #
# General settings:
appName_="AB-Solution"
appVersionInstalled="2.0"
adBlockingDevice_="/tmp/mnt/NAS"
adBlockingState="on"
loggingState="on"
symlinkState="on"
shellState="off"

# Hosts file settings:
hostsFileType="shooter40sw"
hostsFileUpdateDay="Tuesday"
dayOfWeek="2"
hostsFileLastRun="Sep 06 12:40"
hosts_list="http://winhelp2002.mvps.org/hosts.txt
http://someonewhocares.org/hosts/zero/hosts
http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&startdate[day]=&startdate[month]=&startdate[year]=&mimetype=plaintext&useip=0.0.0.0
http://www.malwaredomainlist.com/hostslist/hosts.txt
http://hosts-file.net/ad_servers.txt
http://adaway.org/hosts.txt
http://hosts-file.net/emd.txt
http://hosts-file.net/grm.txt
http://hosts-file.net/mmt.txt"

# Custom IP settings:
customIP="on"
customIPv4="192.168.1.1"

# Ad-blocking stats:
weeklyStats="off"
blockedHosts="191404"
adsBlocked="0"

# Router info:
routerName="RT-AC66U"
architecture="mips"
ipv6_service="disabled"

# Message:
newMessage="0"
message=""

lastConfUpdate="Tue Sep  6 12:52:13 2016"
admin@RT-AC66R-D700:/tmp/home/root#
```

**Comment by decoderman** [comment]
Thank you for your detailed answer. This is a confirmed bug, see the discussion here:
http://www.snbforums.com/threads/ab-solution-2-0-is-out.34530/#post-279085.
I will push out a fix as soon as possible.

**Comment by shounak-de** [comment]
Thanks for the forum link. Also, I wanted to mention this script overwrites my ``/jffs/scripts/post-mount`` Can it be made to append to that file if it already exists?

**Comment by decoderman** [comment]
Yes it does, as I had no clever way of checking my entries are in the file. It should work now with the BIG warning placed in the file. Still, installing other packages such as entware would do the same to you and my script! Not much I can do than save a backup of the file to /adblocking/backup/ before I overwrite it.

**Comment by shounak-de** [comment]
Maybe this?
```
grep -q "AB-Solution added entries via post-mount" /jffs/scripts/post-mount && echo "I found my entry" || echo "Untouched by AB-Solution"
```

**Comment by decoderman** [comment]
That's what the current code does: 
`if grep -q "# DO NOT EDIT THIS MANUALLY" $jScripts/post-mount;then
		echo " Existing $jScripts/post-mount found compatible, no changes necessary."`
Future installs will not have the file replaced.
The "AB-Solution added entries .." Part has been in AB-Solution for a while. In fact I was checking for the presence of  "# generated by AB-Solution" in previous versions. But users edited my parts of the file and I realised I could not depend on it.
So now I have this big WARNING and hope users will be reasonable.

BTW: I found the bug with your restarting error. A fixed version is going to be posted soon. Running the [cu] command will come in handy then. And used for the first time!

**Comment by shounak-de** [comment]
Thank you. My point is that AB-Solution should not (in my opinion, of course) own the post-mount file. It should allow for users own entries. I was already using post-mount to relocate syslog from /jffs to a specified place under /mnt (if my USB drive was mounted) There were other customization as well. 

All of those were wiped out with the absolution install. I had to manually put them back from the backup you made.

**Comment by decoderman** [comment]
I dont own anything on your router.  I have had this discussion about overwriting/replacing more than once. For me, the case is closed. I have a problem if it is too much work to copy/paste a few lines when I coded more than 2000 lines of code for ones convenience.

**Comment by shounak-de** [comment]
My words came out all wrong. I do appreciate the work you've put into it very much.

**Comment by decoderman** [comment]
No problem. The rest of your comments are duly noted.
