### ISSUE TITLE
ext4 not supported but documentation says it is

### ISSUE THREAD

**Issue by alexjj** [decoderman/AB-Solution#7]
On the website it says ext4 formatted USB is supported, however, when I came to install it the installer just says on ext2/3 are supported and didn't accept my ext4.

I'm not bothered about ext4 support, but the website/documentation should reflect this.

Awesome project! 💯 👍

**Comment by TheS1R** [comment]
Support for ext4 is router dependent. Some of the older ASUS routers only support ext2/3.

**Comment by decoderman** [comment]
Routers with MIPS processor support ext2/3. ARM support ext2/3/4.
Your router likely never mounted the thumb drive.

**Comment by alexjj** [comment]
Ah okay. It wasn't an issue at all, I just reformatted the usb stick. I don't know if it warrants a footnote just to say, but probably a very minor detail.

**Comment by decoderman** [comment]
>I don't know if it warrants a footnote just to say, but probably a very minor detail.
Sure does, will add it. Thanks
