### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by computer777** [decoderman/AB-Solution#8]
Is there any chance you would consider including ddwrt into your supported devices list?

**Comment by decoderman** [comment]
I will look into supporting routers running DD-WRT after AB-Solution 4.0 is released. This will not be before 2018.

**Comment by computer777** [comment]
@decoderman , that is awesome! Its worth the wait.

**Comment by decoderman** [comment]
I said I will look into it. Based on the workload expected I will then decide if I support DD-WRT firmware or not.
AB-Solution is a one-man project and I like to keep it that way. But this sets limits to how much time I am willing and able to spend to code and support it. 
This is the deciding question I have to answer to myself when I make the decision.

**Comment by computer777** [comment]
Got it! :smile:
Certainly, I do hope time becomes less of a factor in your decision. But, I can only imagine the time being put in to a project. Anyway, ::fingers::crossed:: 
I was able to use AB solution on xwvortex and it provided much convenience, for sure. @decoderman , take care now.
